name: Static Build

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'Tobias027/python-web'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run build script
        run: |
          chmod +x ./link_bio/remote_build.sh
          ./frontend/remote_build.sh

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update static build
          commit_user_name: Tobias [GitHub Actions]
          commit_user_email: castellarintobiasgmail.com
          commit_author: Tobias <castellarintobias@gmail.com>
